[versions]
kotlin = "1.9.0"
compose = "1.5.0"
gms = "4.4.0"
agp = "8.2.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose" }
com.google.gms.google-services = { id = "com.google.gms.google-services", version.ref = "4.4.1" }

[libraries]
# Jetpack Compose
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.1" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }

# Kotlinx
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }

# Lifecycle + ViewModel
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.2" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.2" }

# Firebase (BOM-managed preferred)
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "32.7.2" }
firebase-core = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "21.6.1" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }

# Accompanist
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.32.0" }

# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.3" }

# Material Components (optional for pre-M3 or mixed use)
material = { group = "com.google.android.material", name = "material", version = "1.11.0" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "32.7.0" }

