[versions]
kotlin = "1.9.0"

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "1.5.0" }
com.google.gms.google-services = { id = "com.google.gms.google-services", version = "4.4.0" }

[libraries]
